// BOOK
export const BOOK_GET_LIST = 'BOOK_GET_LIST';
export const BOOK_CLEAR_STORE = 'BOOK_CLEAR_STORE';

// FAVORITE
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const DELETE_FROM_FAVORITES = 'DELETE_FROM_FAVORITES';
export const IDS_TO_FAVORITES = 'IDS_TO_FAVORITES';
